using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PayoutCalculation : MonoBehaviour
{
    [SerializeField]
    private int x_Distance;
    [SerializeField]
    private int y_Distance;

    [SerializeField]
    private Transform LineContainer;
    [SerializeField]
    private GameObject Line_Prefab;

    [SerializeField]
    private Vector2 InitialLinePosition = new Vector2(-315, 100);
    [SerializeField]
    private List<GameObject> Staticpaylines;
    [SerializeField]
    private List<GameObject> LeftDots;
    [SerializeField]
    private List<GameObject> RightDots;

    GameObject TempLeftDot = null;
    GameObject TempRightDot = null;
    GameObject TempObj = null;

    internal void GeneratePayoutLinesBackend(int index, bool isStatic = false)
    {
        GameObject MyLineObj = Staticpaylines[index];
        MyLineObj.GetComponent<ImageAnimation>().StartAnimation();

        // play the matching left/right dots at the same index
        if (index < LeftDots.Count && index < RightDots.Count)
        {
            GameObject leftDot = LeftDots[index];
            GameObject rightDot = RightDots[index];

            leftDot.GetComponent<ImageAnimation>().StartAnimation();
            rightDot.GetComponent<ImageAnimation>().StartAnimation();

            if (isStatic)
            {
                TempLeftDot = leftDot;
                TempRightDot = rightDot;
            }
        }

        if (isStatic)
        {
            TempObj = MyLineObj;
        }
    }

    //delete the line generated by button hover
    internal void ResetStaticLine()
    {
        if (TempObj != null)
        {
            TempObj.GetComponent<ImageAnimation>().StopAnimation();
            TempObj = null;
        }

        if (TempLeftDot != null)
        {
            TempLeftDot.GetComponent<ImageAnimation>().StopAnimation();
            TempLeftDot = null;
        }

        if (TempRightDot != null)
        {
            TempRightDot.GetComponent<ImageAnimation>().StopAnimation();
            TempRightDot = null;
        }
    }

    //delete all lines
    internal void ResetLines()
    {
        foreach (var child in Staticpaylines)
        {
            child.GetComponent<ImageAnimation>().StopAnimation();
        }

        foreach (var dot in LeftDots)
        {
            dot.GetComponent<ImageAnimation>().StopAnimation();
        }

        foreach (var dot in RightDots)
        {
            dot.GetComponent<ImageAnimation>().StopAnimation();
        }
    }
}
